import Head from "next/head";
import Banner from "../components/banner/banner";
import Card from "../components/card/card";
import SectionCards from "../components/card/section-cards";
import NavBar from "../components/navbar/navbar";
import styles from "../styles/Home.module.css";
import { getPopularVideos, getVideos } from "../lib/videos";

export async function getServerSideProps(context) {
  const marvelVideos = await getVideos("marvel trailer");
  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos("Productivity");
  const travelVideos = await getVideos("indie music");
  const popularVideos = await getPopularVideos();

  return {
    props: {
      marvelVideos,
      disneyVideos,
      travelVideos,
      productivityVideos,
      popularVideos,
    },
  };
}

export default function Home({
  marvelVideos,
  disneyVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
}) {
  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar username="dev.etcraig@gmail.com" />
        <Banner
          title="Avengers"
          subTitle="Rocks... Lots of Rocks."
          imgUrl="/static/Avengers"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title="Marvel" videos={marvelVideos} size="large" />
          <SectionCards title="Disney" videos={disneyVideos} size="small" />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </>
  );
}
